version: "3.4"
############################
# STRICTLY FOR DEVELOPMENT #
############################
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: df.dev
    command: ["yarn", "run", "dev"]
    volumes:
      - .:/user/src/app
    ports:
      - "3000:3000"
      - "5858:5858"
      - "9229:9229"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"